kind: pipeline
type: docker
name: default

steps:
- name: test
  image: node
  commands:
    - npm install
    - npx playwright install-deps
    - npx codeceptjs run
  when:
    event:
      - push
    branch:
      - main

trigger:
  branch:
    - main
  event:
    - push